### ISSUE TITLE
Useless cert_text

### ISSUE THREAD

**Issue by timlegge** [perl-net-saml2/perl-Net-SAML2#123]
https://github.com/perl-net-saml2/perl-Net-SAML2/blob/9d9ac1a793449df9976e8ca2bc8be2cfcb50d837/lib/Net/SAML2/Binding/POST.pm#L68

Need to look at this closer.  Does not appear to be used.

**Comment by timlegge** [comment]
XML::Sig only appears to use the cert_text when signing the xml

**Comment by waterkip** [comment]
I don't think it is useless there.

**Comment by timlegge** [comment]
The point was https://metacpan.org/pod/XML::Sig#cert_text is only used when generating a signature.  It is not used when verifying a certificate - as line 68 is doing.

**Comment by timlegge** [comment]
Wow! I never thought of that use case at all. I'm not entirely sure that's what it was documented for, but I understand why you would want to use it. 

I can take a look at reverting that change and adding documentation for its purpose as you've been using it @waterkip do you have any thoughts?
