### ISSUE TITLE
Check return code for verify_xml

### ISSUE THREAD

**Issue by timlegge** [perl-net-saml2/perl-Net-SAML2#124]
https://github.com/perl-net-saml2/perl-Net-SAML2/blob/9d9ac1a793449df9976e8ca2bc8be2cfcb50d837/lib/Net/SAML2/Binding/POST.pm#L65

verify_xml only returns 1 and croaks if an error occurs in any verification but it is likely a good idea to check that it returns 1 in case someone adds a return somewhere by mistake.

**Comment by waterkip** [comment]
`verify_xml` should croak on failure and not emit other type of return codes tbh. We could also change it to just return.
