### ISSUE TITLE
warn causes fatal error for Dancer

### ISSUE THREAD

**Issue by timlegge** [perl-net-saml2/perl-Net-SAML2#127]
Should any certificate cause an error to be raised the warn is Fatal in Dancer apps:
```
Warning caught during route execution: Can't verify IdP cert: verify: self-signed certificate at ../../blib/lib/Net/SAML2/IdP.pm line 237.
 at /home/tim/perl5/lib/perl5/x86_64-linux/Class/MOP/Method/Wrapped.pm line 166.

```
https://github.com/perl-net-saml2/perl-Net-SAML2/blob/9d9ac1a793449df9976e8ca2bc8be2cfcb50d837/lib/Net/SAML2/IdP.pm#L232

The intent was not to make this a fatal error simply to alert the admin.

**Comment by waterkip** [comment]
To me this is a problem of Dancer. In any module that issues a warn becomes a fatal error in Dancer. I'm not agreeing with Dancer on this.

**Comment by timlegge** [comment]
Thanks to @waterkip on IRC I found the issue was warnings: 1 in xt/testapp/environments/development.yml - change to 0 to ignore
