### ISSUE TITLE
Support for ForceAuthn and IsPassive in AuthnRequest

### ISSUE THREAD

**Issue by dforkner** [perl-net-saml2/perl-Net-SAML2#128]
This is absolutely minor, but we need to set "ForceAuthn=true" on some of our AuthnRequests (which would be done in Net::SAML2::Protocol::AuthnRequest->as_xml()). It would be nice if the module supported this, and perhaps also IsPassive (which is related).  (Spec reference: http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf page 49.)

**Comment by timlegge** [comment]
So something like this:

```
<saml2p:AuthnRequest IssueInstant="2022-11-22T22:46:12Z"
                     Version="2.0"
                     ForceAuthn="true"
                     Destination="https://dev-cqkbrjix.us.auth0.com/samlp/jL77zvH8UIM1XnCikEKF8v4VHTXlZyEB"
                     ID="NETSAML2_3e66dec396b83a7fad0290d82ac865637fab50eacd61443bc963fdac0ace2d1e"
                     xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"
                     xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
  <saml2:Issuer>https://netsaml2-testapp.local</saml2:Issuer>
  <saml2p:NameIDPolicy Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"></saml2p:NameIDPolicy>
</saml2p:AuthnRequest>
```
Fairly straight forward.  I have a working change but I need to take a closer look at it.

**Comment by timlegge** [comment]
I think the change is pretty much ready to commit.  I am travelling on business until Wednesday so I may not get time to merge till Thursday.  Sorry for the delay.
