### ISSUE TITLE
Service Provider (SP) private key

### ISSUE THREAD

**Issue by aaalexby** [perl-net-saml2/perl-Net-SAML2#14]
Net::SAML2::Binding::Redirect required a Service Provider (SP) private key. But Microsoft Azure do not present this key. It allow to download only Certificate.

![image](https://user-images.githubusercontent.com/26674073/106156042-1f1c4d00-6192-11eb-84ea-6b539b46ec78.png)

So, how can I use this code without key?

my $redirect = Net::SAML2::Binding::Redirect->new(
  key => '/path/to/SPsign-nopw-key.pem',      # Service Provider (SP) private key
  url => $sso_url,                            # Service Provider Single Sign Out URL
  param => 'SAMLRequest' OR 'SAMLResponse',   # Type of request
  cert => '/path/to/IdP-cert.pem'             # Service Provider (SP) certificate
);
my $url = $redirect->sign($authnreq);
my $ret = $redirect->verify($url);

**Comment by timlegge** [comment]
The SP service provider is the application the Idp is the Identity Provider (Microsoft Azure in this case)

So the key required here is the applications key that can be used to sign AuthnRequests

TIm

**Comment by aaalexby** [comment]
Thank You!
