### ISSUE TITLE
Azure doesn't like it when 'id' start with a number

### ISSUE THREAD

**Issue by nrathaus** [perl-net-saml2/perl-Net-SAML2#16]
Hi,

When trying to integrate with Azure SAMLv2, I get - sometimes as the ID might be 'correct' this error:
`AADSTS7500529: The value '1a480d8dd87f....' is not a valid SAML ID. The ID must not begin with a number.`

I traced it back to that the authn_request generates a request with an id that starts with '1' (a number), and Azure specifically asks that something non-numerical be placed

Appending an 'id' value to the ID generated solves the problem

However, I do not know how to do this in a manner that isn't Azure specific

Any idea/suggestions?

**Comment by timlegge** [comment]
That should never happen.  Are you using the latest version?  The code is supposed to call generate_id which prepends NETSAML2_

Can I see your code?

**Comment by timlegge** [comment]
see https://github.com/perl-net-saml2/perl-Net-SAML2/commit/a606e2007b0a4a77bf1da54b79f201e95b9b9355

**Comment by nrathaus** [comment]
You are right, I wasn't using the latest

Seems to have solved the problem - I will do more testing if its not resolved, I will reopen
