### ISSUE TITLE
Net-SAML2-0.65-TRIAL: Can not download on meta cpan

### ISSUE THREAD

**Issue by twata1** [perl-net-saml2/perl-Net-SAML2#163]
Hello,

I can not download [Net-SAML2-0.65-TRIAL.tar.gz on meta cpan](https://metacpan.org/release/TIMLEGGE/Net-SAML2-0.65-TRIAL) manually because it seem to me that its Download link is broken.

Thank you,

**Comment by mauke** [comment]
Looks like a metacpan issue. For now, https://www.cpan.org/authors/id/T/TI/TIMLEGGE/Net-SAML2-0.65-TRIAL.tar.gz is available as a workaround.

**Comment by twata1** [comment]
@mauke 

Thank you for your response.

Also, I can not download [XML-Enc-0.09-TRIAL.tar.gz on metacpan](https://metacpan.org/release/TIMLEGGE/XML-Enc-0.09-TRIAL) manually.
For now, I can download https://www.cpan.org/authors/id/T/TI/TIMLEGGE/XML-Enc-0.09-TRIAL.tar.gz !

**Comment by timlegge** [comment]
Thanks for the report.  I am about ready to release the new versions likely this weekend.  It looks like metacpan had an issue when I was uploading them to cpan

**Comment by timlegge** [comment]
https://metacpan.org/release/TIMLEGGE/Net-SAML2-0.66-TRIAL is now available - no changes just a version increment
