### ISSUE TITLE
Is a backport feasible?

### ISSUE THREAD

**Issue by rogerrohrbach** [perl-net-saml2/perl-Net-SAML2#227]
We're running a Ball of Mud legacy system on Perl 5.010001.  Is it a fool's errand to attempt to backport `Net::SAML2` to this version of Perl?  There are only a few dependencies we're not able to install:
```
Crypt::OpenSSL::Verify
Crypt::OpenSSL::X509
XML::Enc
XML::Sig
```
Any tips or stern warnings appreciated before I dive in.

**Comment by timlegge** [comment]
It should be quite doable.   We are willing to accept PRs.

**Comment by rogerrohrbach** [comment]
Actually, our system runs under Perl 5.10.1, and it looks like the package will work as is.  I've got all its dependencies successfully installed, save this one:
```
requires "perl" => "5.014";
```
`cpanm` reports:
```
Installing the dependencies failed: Your Perl (5.010001) is not in the range '5.014'
```
This is is because, mystifyingly, `cpanm` is hopelessly confused about the Perl version:
```
$ cpanm -V
cpanm (App::cpanminus) version 1.7046 (/srv/sequoia/.plenv/versions/5.10.1/bin/cpanm)
perl version 5.010001 (/srv/sequoia/.plenv/versions/5.10.1/bin/perl5.10.1)
```

Not sure where to go from here, but I'll close this issue.

**Comment by timlegge** [comment]
Which module are you having issues with now?

Which requires "perl" => "5.014"?

**Comment by rogerrohrbach** [comment]
> Which module are you having issues with now?
> 
> Which requires "perl" => "5.014"?

That's in the [cpanfile](https://github.com/perl-net-saml2/perl-Net-SAML2/blob/0fc0914a4a4ec79b39e30e7fd747393c517fbc96/cpanfile#L42).  But don't worry about it—I discovered that whoever hand-built our version of Perl 5.10.1 left this in `META.yml`:
```
version: 5.010001
```
🙄.

**Comment by rogerrohrbach** [comment]
Just following up: that Perl version business was a red herring—I didn't understand that 5.010001 = 5.10.1.

We're successfully using Net::SAML2 0.62, which declares a dependency on Perl 5.08.
