### ISSUE TITLE
I was using cert_text in 0.74

### ISSUE THREAD

**Issue by max-m-s** [perl-net-saml2/perl-Net-SAML2#229]
I was passing a certificate from the IDP metadata XML to POST as follows:

```
  my $xml = read_text($xml_file);
  my $idp = Net::SAML2::IdP->new_from_xml(
        xml => $xml,        # URL where the xml is located
        cacert => $cacert   # Filename of the Identity Providers CACert
  );
  my $post = Net::SAML2::Binding::POST->new(
        cacert => $cacert,
        cert_text => ${$idp->cert('signing')}[0],
  );
  $ret = $post->handle_response(
        $samlB64
  );
```

If I didn't provide it, I would get "Unrecognized key type or no KeyInfo in document" from XML::Sig.

Now I get that error regardless. Looks like fix #123 removed it.

Is there another way to pass down the certificate from the IdP object to POST->handle_response() that I am missing? I see a file name can be passed as "cert" but I'm not keen on the idea of writing and reading a file at run-time, or manually extracting it.

Otherwise, could "cert_text" be added back in? I'll have to manually downgrade back to 0.74 for now.

**Comment by timlegge** [comment]
Wow! I never thought of that use case at all. I'm not entirely sure that's what it was documented for, but I understand why you would want to use it.

I can take a look at reverting that change and adding documentation for its purpose as you've been using it @waterkip do you have any thoughts?

**Comment by timlegge** [comment]
I have a PR submitted to fix the issue.  I cannot test right now as XML::LibXML is acting up for me...

**Comment by waterkip** [comment]
Adding it back in is a small change I think. Will merge the PR
