### ISSUE TITLE
Allow consumers to inject a custom XML::Sig (like) object for XML signature validation

### ISSUE THREAD

**Issue by waterkip** [perl-net-saml2/perl-Net-SAML2#4]

**Comment by timlegge** [comment]
I am releasing a release version of XML::Sig today with significant improvements to the verification of signed XML.  My plan is to essentially replace Net::SAML2::XML::Sig with a new version of XML::Sig.  The previous version of XML::Sig had all the improvements of Net::SAML2::XML::Sig backported and I have fixed a number of verification issues espepcially around DSA and interoperability with other XML signers
