### ISSUE TITLE
Signing the metadata should be optional

### ISSUE THREAD

**Issue by timlegge** [perl-net-saml2/perl-Net-SAML2#47]
https://github.com/perl-net-saml2/perl-Net-SAML2/blob/ea262ce764bf5e91d9bfb6390475e012010498b3/lib/Net/SAML2/SP.pm#L424

**Comment by timlegge** [comment]
Either works, I have not been concerned enough to look at this as of late but if it is causing issues I can (or a PR is welcome too)

**Comment by waterkip** [comment]
We fixed this in GH#64
