### ISSUE TITLE
Signature of metadata is in the incorrect spot

### ISSUE THREAD

**Issue by waterkip** [perl-net-saml2/perl-Net-SAML2#61]
Because of the renewed development on Net::SAML2 I'm rewriting parts of our old Net::SAML2 implementation. I'm currently hitting a a bug in Net::SAML2 (git/cpan version 0.55).

According to the specs[^1][^2] the xpath to the signature element should be something like this:

`/md:EntityDescriptor/ds:Signature`

In Net::SAML2 this is not the case and the signature is found in:

`/md:EntityDescriptor/md:SPSSODescriptor/ds:Signature`

[^1]: https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf
[^2]: https://en.wikipedia.org/wiki/SAML_metadata

**Comment by waterkip** [comment]
I'll work on a testsuite thing and than I'll look into a PR later.

**Comment by timlegge** [comment]
On a related note have you looked at the "improvements" I made to the testapp?  It now allows you to easily test against multiple IdPs.

**Comment by waterkip** [comment]
No, I haven't. I did have a jab at autogenerating certs before/after a testsuite run. It requires openssl on the CLI tho, so maybe not that useful for Net::SAML2

**Comment by timlegge** [comment]
See https://github.com/perl-net-saml2/perl-Net-SAML2/blob/master/xt/testapp/README.md
